#!/bin/bash

docker run \
       --rm \
       -v "$(pwd):/usr/src/myapp" \
       -w /usr/src/myapp \
       -e GOARCH=amd64 \
       -e CGO_ENABLED=0 \
       golang:1.15.6 \
       go build -o terraform-provider-aws_v2.70.0_x4 -ldflags="-s -w" -v
